name: publish-prod

on:
  push:
    branches: [ "master" ]

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish the hello-docker Docker image
        run: |
          docker build . --tag ghcr.io/anaelr/g_docker:production
          docker push ghcr.io/anaelr/g_docker:production